version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/wan_nyan_pod
      - public-data:/wan_nyan_pod/public
      - tmp-data:/wan_nyan_pod/tmp
      - log-data:/wan_nyan_pod/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
  web:
    build: 
      context: containers/nginx
    volumes:
      - public-data:/wan_nyan_pod/public
      - tmp-data:/wan_nyan_pod/tmp
      - .:/wan_nyan_pod
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql_data: