version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: ${WEB_COMMAND}
    volumes:
      - .:/wan_nyan_pod
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: db
    ports:
      - '3306:3306'
    expose:
    # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
volumes:
  bundle:
  mysql_data: